### ISSUE TITLE
Venus Pitcher Pregnancy Error

### ISSUE THREAD

**Issue by malincar** [Fenoxo/sourceTiTS#274]
I suspect this happened because I had unfertilized seeds that were scheduled to lay in the span of time I got them fertilized. This message appeared immediately after an Elder Venus Pitcher encounter in which the seeds were fertilized.

Something bad happened! Please report this message:

TypeError: Error #1009
	at classes::TiTS/venusPitcherLayUnfertilizedEgg()
	at MethodInfo-719()
	at classes::TiTS/mainGameMenu()
	at classes::TiTS/buttonClick()

**Comment by Gedan** [comment]
A good guess; I'm not entirely sure that's the root cause because of how the mechanics come together (it'd basically be an almost infinitesimally small chance to happen, way too minute for it to be the cause of so many of the reports) because of the order-of-execution in play. You'd basically have to have the actual conversion from unfertilized to fertilized happen in the same processTime() block that also triggers an unfertilized pod to be pushed into the event stack.

I've wrapped a check around it anyway, so we'll see.
