### ISSUE TITLE
Lane submission state inconsistencies

### ISSUE THREAD

**Issue by littlebeast** [Fenoxo/sourceTiTS#354]
When interacting with Lane with two (or more) of her buffs, all the interactions with her *except* being hypnotized are as though my character has been hypnotized completely into a slave.  It even allows me to choose the "Taxes" option in the "Services" menu.

I understand this might be intentional, to allow the impatient quicker access to the sexy content, but it's confusing and kind of ruins the buildup.

Also, the time *before* she did the full submission hypnosis, there was a follow-up "tax" after the hypnosis.  Which also kind of makes no sense.

I'm on the latest public build so disregard this if you've already fixed these.

**Comment by Fenoxo** [comment]
Leavin' dis one for Gedtron.

**Comment by Murphy540** [comment]
If you already have one of the stat hypnosis effects and get hypnotized again (even if you're just refreshing the one you already have) Lane gives you the "Lane Hypnosis" hidden effect. If you enter with Lane Hypnosis, under the "Talk" and "Services" menus you get the hypnotized effects, but you still can't get the "Taxes" in the entry menu until you're fully hypnotized.

As for the tax before the submission hypnosis, that's because of the logic in the scenes.

There's also the issue of the hypnosis level scenes playing the next level when it increases. It increments, then plays the scene rather than vice-versa. I'm not sure if this is intended behavior or not, but I assume it's not.

(example: at hypnosis level 0, Lane plays the "bites his/her lip" scenes, at level 1, plays the "hums to his/herself" scenes, but the final scene for level 0 (the one that triggers the transition) will play a level 1 scene instead)
