### ISSUE TITLE
Bovine "issues"

### ISSUE THREAD

**Issue by Otaku-chan** [Fenoxo/sourceTiTS#469]
This has more to do with how the program reads values that it doesn't normally set, than actually being a bug. The following things are some I experienced while fiddling around with Minerva.

furred skin + bovine face = monstrously shaggy fur on bovine face.

bovine face + high feminity = Mentions nose in muzzle description, and again, but as "cute and small" in general face description.

four bovine legs = centaur body instead of holstaur body.

bovine cock = despite constant mention of "bull cocks" and "cow cocks" throughout New Texas, the game spits out errors if the PC has the cock type set to bovine.

-------------------------------------------------------

Having items that can make you a minotaur or holstaur legitimately in game would be nice.

**Comment by Jacques00** [comment]
That usually comes down to writing. If they are not written for, they normally won't show up in game. Certain types will be implemented once they are actually written for the game--like having a transformation item or event that enables such a type to be attained. Due to this, not all types are supported for all pieces of anatomy. So if  you're using Minerva, you're working outside the boundaries of what is possible in-game.

The bovine faces are probably a carryover from CoC, so they are representative of monstrous minotaur faces. I can see them having some variation with respect to femininity, maybe, but they are impossible to get in-game anyway. The nose inconsistency is glaring though (not only for bovine faces, but other faces as well), so maybe the mention of the adorable/button nose could be excluded from the faceDesc() for some faces (maybe faces with the muzzled and/or long flags--or the specific face types themselves).

Bovine and equine are interchangeable from the waist down it seems. Again, like stated before, this kind of anatomy type will probably be updated once there is writing for it, otherwise, it's a stand-in until something newer/better/faster/stronger is implemented. Udders/crotchboobs, when?

Penis descriptions do not fully support the bovine type as of yet, so there will need to be some writing for that to make it happen. Any bestial bovine transformation usually uses the equine type instead.

**Comment by Fenoxo** [comment]
Bullcocks look crappy, hence why CoC minotaurs and New Texans got given other endowments. New Texan dudes are often referred to as "bulls", so the description in scenes is appropriate in that regard.

Looks like JCup did a bunch of stuff I'll have to review, but this isn't a bug - it's you putting values in places that the game isn't made to handle.

**Comment by Otaku-chan** [comment]
I tried to say as much in the e-mails I brought it up in, but I was told to
post it here, so I did.

I would still like to see bovine cocks, minotaurs, and holstaurs become
things for the player character, though.
